version: '3.8'

services:

    app:
        build: .
        container_name: app
        volumes:
          - .:/var/www
        user: 'www-data:www-data'



    nginx:  
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
        - "8000:80"
        volumes:
          - .:/var/www
    redis:
      image: redis:alpine
      expose:
        - 6379